# Generated by Django 3.1.7 on 2021-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key_ref', models.UUIDField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=512)),
                ('init_vector', models.CharField(max_length=512)),
                ('expire_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
