# Generated by Django 3.1.7 on 2021-04-21 09:31

from django.db import migrations
from django_celery_beat.models import MINUTES


def create_cleanup_schedule(apps, schema_editor):

    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')  # noqa
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')  # noqa

    schedule, created = IntervalSchedule.objects.get_or_create(
        every=1,
        period=MINUTES,

    )
    PeriodicTask.objects.create(
        interval=schedule,
        name='Deleting expired Keys',
        task='key_server.key_management_system.tasks.delete_expired_keys'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('key_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_cleanup_schedule)
    ]
