# Generated by Django 3.1.7 on 2021-05-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_management_system', '0002_auto_20210421_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={'verbose_name': 'key', 'verbose_name_plural': 'keys'},
        ),
    ]
